// Common emoji dataset for autocomplete
export interface EmojiEntry {
  name: string;
  emoji: string;
  keywords: string[];
}

export const EMOJI_DATA: EmojiEntry[] = [
  // Smileys
  { name: "grinning", emoji: "😀", keywords: ["happy", "smile"] },
  { name: "grin", emoji: "😁", keywords: ["happy", "smile"] },
  { name: "joy", emoji: "😂", keywords: ["laugh", "crying", "tears"] },
  { name: "rofl", emoji: "🤣", keywords: ["laugh", "rolling"] },
  { name: "smile", emoji: "😊", keywords: ["happy", "blush"] },
  { name: "sweat_smile", emoji: "😅", keywords: ["nervous", "awkward"] },
  { name: "laughing", emoji: "😆", keywords: ["happy", "haha"] },
  { name: "wink", emoji: "😉", keywords: ["flirt"] },
  { name: "blush", emoji: "😊", keywords: ["happy", "shy"] },
  { name: "yum", emoji: "😋", keywords: ["tongue", "delicious"] },
  { name: "sunglasses", emoji: "😎", keywords: ["cool"] },
  { name: "heart_eyes", emoji: "😍", keywords: ["love", "crush"] },
  { name: "kissing_heart", emoji: "😘", keywords: ["love", "kiss"] },
  { name: "kissing", emoji: "😗", keywords: ["kiss"] },
  { name: "thinking", emoji: "🤔", keywords: ["hmm", "consider"] },
  { name: "neutral_face", emoji: "😐", keywords: ["meh"] },
  { name: "expressionless", emoji: "😑", keywords: ["blank"] },
  { name: "unamused", emoji: "😒", keywords: ["meh", "bored"] },
  { name: "rolling_eyes", emoji: "🙄", keywords: ["whatever"] },
  { name: "grimacing", emoji: "😬", keywords: ["awkward", "yikes"] },
  { name: "relieved", emoji: "😌", keywords: ["calm", "peaceful"] },
  { name: "pensive", emoji: "😔", keywords: ["sad", "thoughtful"] },
  { name: "sleepy", emoji: "😪", keywords: ["tired"] },
  { name: "drooling", emoji: "🤤", keywords: ["hungry"] },
  { name: "sleeping", emoji: "😴", keywords: ["zzz", "tired"] },
  { name: "mask", emoji: "😷", keywords: ["sick", "covid"] },
  { name: "nerd", emoji: "🤓", keywords: ["glasses", "geek"] },
  { name: "confused", emoji: "😕", keywords: ["uncertain"] },
  { name: "worried", emoji: "😟", keywords: ["nervous", "anxious"] },
  { name: "frowning", emoji: "😦", keywords: ["sad"] },
  { name: "anguished", emoji: "😧", keywords: ["shocked", "sad"] },
  { name: "fearful", emoji: "😨", keywords: ["scared"] },
  { name: "cry", emoji: "😢", keywords: ["sad", "tear"] },
  { name: "sob", emoji: "😭", keywords: ["crying", "sad"] },
  { name: "scream", emoji: "😱", keywords: ["scared", "shocked"] },
  { name: "angry", emoji: "😠", keywords: ["mad"] },
  { name: "rage", emoji: "🤬", keywords: ["cursing", "angry"] },
  { name: "triumph", emoji: "😤", keywords: ["frustrated", "huff"] },
  { name: "skull", emoji: "💀", keywords: ["dead", "death"] },
  { name: "poop", emoji: "💩", keywords: ["shit"] },
  { name: "clown", emoji: "🤡", keywords: ["funny"] },
  { name: "ghost", emoji: "👻", keywords: ["halloween", "spooky"] },
  { name: "alien", emoji: "👽", keywords: ["ufo", "space"] },
  { name: "robot", emoji: "🤖", keywords: ["bot", "ai"] },
  { name: "smiley_cat", emoji: "😺", keywords: ["cat", "happy"] },
  { name: "see_no_evil", emoji: "🙈", keywords: ["monkey", "shy"] },
  { name: "hear_no_evil", emoji: "🙉", keywords: ["monkey"] },
  { name: "speak_no_evil", emoji: "🙊", keywords: ["monkey", "quiet"] },
  { name: "wave", emoji: "👋", keywords: ["hello", "bye"] },
  { name: "raised_hand", emoji: "✋", keywords: ["stop", "high five"] },
  { name: "ok_hand", emoji: "👌", keywords: ["perfect", "okay"] },
  { name: "pinching", emoji: "🤏", keywords: ["tiny", "small"] },
  { name: "victory", emoji: "✌️", keywords: ["peace", "two"] },
  { name: "crossed_fingers", emoji: "🤞", keywords: ["luck", "hope"] },
  { name: "love_you", emoji: "🤟", keywords: ["ily"] },
  { name: "metal", emoji: "🤘", keywords: ["rock"] },
  { name: "call_me", emoji: "🤙", keywords: ["phone", "shaka"] },
  { name: "point_left", emoji: "👈", keywords: ["left"] },
  { name: "point_right", emoji: "👉", keywords: ["right"] },
  { name: "point_up", emoji: "👆", keywords: ["up"] },
  { name: "point_down", emoji: "👇", keywords: ["down"] },
  { name: "middle_finger", emoji: "🖕", keywords: ["fu"] },
  { name: "thumbsup", emoji: "👍", keywords: ["yes", "approve", "+1"] },
  { name: "thumbsdown", emoji: "👎", keywords: ["no", "disapprove", "-1"] },
  { name: "fist", emoji: "✊", keywords: ["punch", "power"] },
  { name: "punch", emoji: "👊", keywords: ["fist bump"] },
  { name: "clap", emoji: "👏", keywords: ["applause", "bravo"] },
  { name: "raised_hands", emoji: "🙌", keywords: ["celebration", "praise"] },
  { name: "handshake", emoji: "🤝", keywords: ["deal", "agree"] },
  { name: "pray", emoji: "🙏", keywords: ["please", "thanks", "namaste"] },
  { name: "writing_hand", emoji: "✍️", keywords: ["write"] },
  { name: "muscle", emoji: "💪", keywords: ["strong", "flex"] },
  { name: "brain", emoji: "🧠", keywords: ["smart", "think"] },
  { name: "eyes", emoji: "👀", keywords: ["look", "see", "watching"] },
  { name: "eye", emoji: "👁️", keywords: ["see"] },
  { name: "tongue", emoji: "👅", keywords: ["lick", "taste"] },
  { name: "ear", emoji: "👂", keywords: ["listen", "hear"] },
  { name: "nose", emoji: "👃", keywords: ["smell"] },
  { name: "baby", emoji: "👶", keywords: ["child", "infant"] },
  { name: "shrug", emoji: "🤷", keywords: ["idk", "dunno"] },
  { name: "facepalm", emoji: "🤦", keywords: ["smh"] },
  { name: "salute", emoji: "🫡", keywords: ["respect", "yes sir"] },
  // Hearts & Emotions
  { name: "heart", emoji: "❤️", keywords: ["love", "red"] },
  { name: "orange_heart", emoji: "🧡", keywords: ["love"] },
  { name: "yellow_heart", emoji: "💛", keywords: ["love"] },
  { name: "green_heart", emoji: "💚", keywords: ["love"] },
  { name: "blue_heart", emoji: "💙", keywords: ["love"] },
  { name: "purple_heart", emoji: "💜", keywords: ["love"] },
  { name: "black_heart", emoji: "🖤", keywords: ["love", "dark"] },
  { name: "white_heart", emoji: "🤍", keywords: ["love", "pure"] },
  { name: "broken_heart", emoji: "💔", keywords: ["sad", "breakup"] },
  { name: "fire", emoji: "🔥", keywords: ["hot", "lit", "flame"] },
  { name: "sparkles", emoji: "✨", keywords: ["magic", "shine", "new"] },
  { name: "star", emoji: "⭐", keywords: ["favorite"] },
  { name: "star2", emoji: "🌟", keywords: ["glowing"] },
  { name: "zap", emoji: "⚡", keywords: ["lightning", "electric"] },
  { name: "boom", emoji: "💥", keywords: ["explosion", "collision"] },
  { name: "hundred", emoji: "💯", keywords: ["perfect", "100"] },
  { name: "warning", emoji: "⚠️", keywords: ["caution", "alert"] },
  // Animals
  { name: "dog", emoji: "🐕", keywords: ["pet", "puppy"] },
  { name: "cat", emoji: "🐈", keywords: ["pet", "kitty"] },
  { name: "fox", emoji: "🦊", keywords: ["clever"] },
  { name: "bear", emoji: "🐻", keywords: ["teddy"] },
  { name: "panda", emoji: "🐼", keywords: ["bear"] },
  { name: "unicorn", emoji: "🦄", keywords: ["magic", "fantasy"] },
  { name: "butterfly", emoji: "🦋", keywords: ["pretty", "insect"] },
  { name: "bug", emoji: "🐛", keywords: ["insect", "debug"] },
  { name: "snake", emoji: "🐍", keywords: ["python"] },
  { name: "turtle", emoji: "🐢", keywords: ["slow"] },
  { name: "octopus", emoji: "🐙", keywords: ["tentacles"] },
  { name: "whale", emoji: "🐳", keywords: ["ocean"] },
  { name: "dolphin", emoji: "🐬", keywords: ["ocean"] },
  { name: "fish", emoji: "🐟", keywords: ["ocean"] },
  { name: "chicken", emoji: "🐔", keywords: ["bird"] },
  { name: "penguin", emoji: "🐧", keywords: ["bird", "cold"] },
  { name: "owl", emoji: "🦉", keywords: ["bird", "wise"] },
  { name: "bee", emoji: "🐝", keywords: ["honey", "insect"] },
  { name: "crab", emoji: "🦀", keywords: ["rust"] },
  { name: "shrimp", emoji: "🦐", keywords: ["seafood"] },
  { name: "monkey", emoji: "🐒", keywords: ["ape"] },
  { name: "gorilla", emoji: "🦍", keywords: ["ape"] },
  // Food & Drink
  { name: "apple", emoji: "🍎", keywords: ["fruit", "red"] },
  { name: "pizza", emoji: "🍕", keywords: ["food"] },
  { name: "hamburger", emoji: "🍔", keywords: ["burger", "food"] },
  { name: "fries", emoji: "🍟", keywords: ["food", "chips"] },
  { name: "hotdog", emoji: "🌭", keywords: ["food"] },
  { name: "taco", emoji: "🌮", keywords: ["food", "mexican"] },
  { name: "burrito", emoji: "🌯", keywords: ["food", "wrap"] },
  { name: "sushi", emoji: "🍣", keywords: ["food", "japanese"] },
  { name: "ramen", emoji: "🍜", keywords: ["food", "noodles"] },
  { name: "cookie", emoji: "🍪", keywords: ["food", "sweet"] },
  { name: "cake", emoji: "🎂", keywords: ["birthday", "food"] },
  { name: "ice_cream", emoji: "🍦", keywords: ["dessert", "cold"] },
  { name: "donut", emoji: "🍩", keywords: ["food", "sweet"] },
  { name: "coffee", emoji: "☕", keywords: ["drink", "hot", "morning"] },
  { name: "tea", emoji: "🍵", keywords: ["drink", "hot"] },
  { name: "beer", emoji: "🍺", keywords: ["drink", "alcohol"] },
  { name: "wine", emoji: "🍷", keywords: ["drink", "alcohol"] },
  { name: "cocktail", emoji: "🍸", keywords: ["drink", "alcohol"] },
  { name: "champagne", emoji: "🍾", keywords: ["drink", "celebrate"] },
  { name: "avocado", emoji: "🥑", keywords: ["food", "guac"] },
  { name: "egg", emoji: "🥚", keywords: ["food"] },
  { name: "banana", emoji: "🍌", keywords: ["fruit"] },
  { name: "watermelon", emoji: "🍉", keywords: ["fruit", "summer"] },
  { name: "strawberry", emoji: "🍓", keywords: ["fruit", "berry"] },
  { name: "peach", emoji: "🍑", keywords: ["fruit", "butt"] },
  { name: "cherry", emoji: "🍒", keywords: ["fruit"] },
  // Activities & Objects
  { name: "soccer", emoji: "⚽", keywords: ["ball", "sport", "football"] },
  { name: "basketball", emoji: "🏀", keywords: ["ball", "sport"] },
  { name: "football", emoji: "🏈", keywords: ["ball", "sport"] },
  { name: "baseball", emoji: "⚾", keywords: ["ball", "sport"] },
  { name: "trophy", emoji: "🏆", keywords: ["winner", "award"] },
  { name: "medal", emoji: "🏅", keywords: ["winner", "award"] },
  { name: "guitar", emoji: "🎸", keywords: ["music", "rock"] },
  { name: "microphone", emoji: "🎤", keywords: ["music", "singing"] },
  { name: "headphones", emoji: "🎧", keywords: ["music", "audio"] },
  { name: "art", emoji: "🎨", keywords: ["painting", "creative"] },
  { name: "film", emoji: "🎬", keywords: ["movie", "cinema"] },
  { name: "camera", emoji: "📷", keywords: ["photo"] },
  { name: "video_camera", emoji: "📹", keywords: ["recording"] },
  { name: "computer", emoji: "💻", keywords: ["laptop", "mac"] },
  { name: "phone", emoji: "📱", keywords: ["mobile", "cell"] },
  { name: "keyboard", emoji: "⌨️", keywords: ["typing", "computer"] },
  { name: "bulb", emoji: "💡", keywords: ["idea", "light"] },
  { name: "book", emoji: "📖", keywords: ["read", "study"] },
  { name: "bookmark", emoji: "🔖", keywords: ["save"] },
  { name: "link", emoji: "🔗", keywords: ["url", "chain"] },
  { name: "scissors", emoji: "✂️", keywords: ["cut"] },
  { name: "lock", emoji: "🔒", keywords: ["secure", "private"] },
  { name: "key", emoji: "🔑", keywords: ["password", "unlock"] },
  { name: "hammer", emoji: "🔨", keywords: ["tool", "build"] },
  { name: "wrench", emoji: "🔧", keywords: ["tool", "fix"] },
  { name: "gear", emoji: "⚙️", keywords: ["settings", "config"] },
  { name: "bomb", emoji: "💣", keywords: ["explosion"] },
  { name: "gun", emoji: "🔫", keywords: ["water", "weapon"] },
  { name: "pill", emoji: "💊", keywords: ["medicine", "drug"] },
  { name: "money", emoji: "💰", keywords: ["bag", "rich", "cash"] },
  { name: "dollar", emoji: "💵", keywords: ["money", "cash"] },
  { name: "gem", emoji: "💎", keywords: ["diamond", "jewel"] },
  { name: "gift", emoji: "🎁", keywords: ["present", "birthday"] },
  { name: "balloon", emoji: "🎈", keywords: ["party"] },
  { name: "tada", emoji: "🎉", keywords: ["party", "celebration", "hooray"] },
  { name: "confetti", emoji: "🎊", keywords: ["party", "celebration"] },
  { name: "ribbon", emoji: "🎀", keywords: ["bow", "gift"] },
  { name: "bell", emoji: "🔔", keywords: ["notification", "ring"] },
  { name: "music", emoji: "🎵", keywords: ["note", "song"] },
  { name: "notes", emoji: "🎶", keywords: ["music", "song"] },
  { name: "megaphone", emoji: "📣", keywords: ["announcement"] },
  { name: "loudspeaker", emoji: "📢", keywords: ["announcement", "loud"] },
  { name: "mail", emoji: "📧", keywords: ["email", "letter"] },
  { name: "envelope", emoji: "✉️", keywords: ["mail", "letter"] },
  { name: "memo", emoji: "📝", keywords: ["note", "write"] },
  { name: "calendar", emoji: "📅", keywords: ["date", "schedule"] },
  { name: "chart", emoji: "📈", keywords: ["graph", "up", "stonks"] },
  { name: "chart_down", emoji: "📉", keywords: ["graph", "down"] },
  { name: "pin", emoji: "📌", keywords: ["thumbtack", "location"] },
  { name: "paperclip", emoji: "📎", keywords: ["attach"] },
  { name: "trash", emoji: "🗑️", keywords: ["delete", "garbage"] },
  { name: "inbox", emoji: "📥", keywords: ["download", "mail"] },
  // Nature & Weather
  { name: "sun", emoji: "☀️", keywords: ["sunny", "bright", "hot"] },
  { name: "moon", emoji: "🌙", keywords: ["night", "crescent"] },
  { name: "cloud", emoji: "☁️", keywords: ["weather"] },
  { name: "rain", emoji: "🌧️", keywords: ["weather", "wet"] },
  { name: "snow", emoji: "❄️", keywords: ["cold", "winter", "frozen"] },
  { name: "rainbow", emoji: "🌈", keywords: ["pride", "colorful"] },
  { name: "tornado", emoji: "🌪️", keywords: ["storm"] },
  { name: "ocean", emoji: "🌊", keywords: ["wave", "water", "sea"] },
  { name: "flower", emoji: "🌸", keywords: ["cherry blossom", "spring"] },
  { name: "rose", emoji: "🌹", keywords: ["flower", "love"] },
  { name: "sunflower", emoji: "🌻", keywords: ["flower"] },
  { name: "herb", emoji: "🌿", keywords: ["plant", "leaf"] },
  { name: "four_leaf_clover", emoji: "🍀", keywords: ["luck", "irish"] },
  { name: "tree", emoji: "🌳", keywords: ["nature"] },
  { name: "palm_tree", emoji: "🌴", keywords: ["tropical", "beach"] },
  { name: "cactus", emoji: "🌵", keywords: ["desert"] },
  { name: "mushroom", emoji: "🍄", keywords: ["fungus"] },
  { name: "earth", emoji: "🌍", keywords: ["globe", "world", "planet"] },
  // Transport & Places
  { name: "car", emoji: "🚗", keywords: ["auto", "vehicle"] },
  { name: "taxi", emoji: "🚕", keywords: ["cab"] },
  { name: "bus", emoji: "🚌", keywords: ["vehicle"] },
  { name: "rocket", emoji: "🚀", keywords: ["space", "launch", "fast"] },
  { name: "airplane", emoji: "✈️", keywords: ["travel", "fly"] },
  { name: "ship", emoji: "🚢", keywords: ["boat", "cruise"] },
  { name: "house", emoji: "🏠", keywords: ["home"] },
  { name: "building", emoji: "🏢", keywords: ["office"] },
  { name: "hospital", emoji: "🏥", keywords: ["doctor"] },
  { name: "school", emoji: "🏫", keywords: ["education"] },
  { name: "tent", emoji: "⛺", keywords: ["camping"] },
  // Symbols
  { name: "check", emoji: "✅", keywords: ["yes", "done", "correct"] },
  { name: "x", emoji: "❌", keywords: ["no", "wrong", "delete"] },
  { name: "question", emoji: "❓", keywords: ["what", "confused"] },
  { name: "exclamation", emoji: "❗", keywords: ["important", "alert"] },
  { name: "plus", emoji: "➕", keywords: ["add"] },
  { name: "minus", emoji: "➖", keywords: ["subtract"] },
  { name: "infinity", emoji: "♾️", keywords: ["forever"] },
  { name: "recycle", emoji: "♻️", keywords: ["environment"] },
  { name: "white_flag", emoji: "🏳️", keywords: ["surrender"] },
  { name: "checkered_flag", emoji: "🏁", keywords: ["finish", "race"] },
  { name: "pirate_flag", emoji: "🏴‍☠️", keywords: ["jolly roger"] },
  { name: "triangular_flag", emoji: "🚩", keywords: ["red flag", "warning"] },
  { name: "crown", emoji: "👑", keywords: ["king", "queen", "royal"] },
  { name: "ring", emoji: "💍", keywords: ["wedding", "engaged"] },
  // Misc fun
  { name: "pls", emoji: "🥺", keywords: ["please", "puppy eyes", "begging"] },
  { name: "moai", emoji: "🗿", keywords: ["stone", "easter island"] },
  { name: "moyai", emoji: "🗿", keywords: ["stone", "bruh"] },
  { name: "eggplant", emoji: "🍆", keywords: ["vegetable", "aubergine"] },
  { name: "hot_pepper", emoji: "🌶️", keywords: ["spicy"] },
  { name: "corn", emoji: "🌽", keywords: ["maize"] },
  { name: "popcorn", emoji: "🍿", keywords: ["movie", "snack"] },
  { name: "christmas_tree", emoji: "🎄", keywords: ["holiday"] },
  { name: "jack_o_lantern", emoji: "🎃", keywords: ["halloween", "pumpkin"] },
  { name: "snowman", emoji: "⛄", keywords: ["winter", "cold"] },
  { name: "santa", emoji: "🎅", keywords: ["christmas"] },
  { name: "wave_dark", emoji: "👋🏿", keywords: ["hello", "bye"] },
  { name: "ok", emoji: "🆗", keywords: ["okay"] },
  { name: "cool", emoji: "🆒", keywords: ["nice"] },
  { name: "new", emoji: "🆕", keywords: ["fresh"] },
  { name: "free", emoji: "🆓", keywords: [] },
  { name: "sos", emoji: "🆘", keywords: ["help", "emergency"] },
  { name: "no_entry", emoji: "⛔", keywords: ["stop", "forbidden"] },
  { name: "up", emoji: "⬆️", keywords: ["arrow"] },
  { name: "down_arrow", emoji: "⬇️", keywords: ["arrow"] },
  { name: "left_arrow", emoji: "⬅️", keywords: ["arrow"] },
  { name: "right_arrow", emoji: "➡️", keywords: ["arrow"] },
  { name: "party_popper", emoji: "🎉", keywords: ["celebrate", "yay"] },
  { name: "sparkle", emoji: "❇️", keywords: ["shine"] },
  { name: "dizzy", emoji: "😵", keywords: ["spiral", "confused"] },
  { name: "sick", emoji: "🤢", keywords: ["nauseous", "green"] },
  { name: "vomit", emoji: "🤮", keywords: ["throw up", "sick"] },
  { name: "hot", emoji: "🥵", keywords: ["temperature", "sweating"] },
  { name: "cold_face", emoji: "🥶", keywords: ["freezing", "temperature"] },
  { name: "mind_blown", emoji: "🤯", keywords: ["exploding head", "shocked"] },
  { name: "cowboy", emoji: "🤠", keywords: ["hat", "western"] },
  { name: "disguise", emoji: "🥸", keywords: ["glasses", "nose", "mustache"] },
  { name: "devil", emoji: "😈", keywords: ["evil", "horns"] },
  { name: "imp", emoji: "👿", keywords: ["angry devil"] },
  { name: "angel", emoji: "😇", keywords: ["halo", "innocent"] },
  { name: "smirk", emoji: "😏", keywords: ["suggestive", "flirty"] },
  { name: "upside_down", emoji: "🙃", keywords: ["sarcasm", "silly"] },
  { name: "melting", emoji: "🫠", keywords: ["embarrassed", "hot"] },
  { name: "zipper_mouth", emoji: "🤐", keywords: ["secret", "quiet", "zip"] },
  { name: "money_mouth", emoji: "🤑", keywords: ["rich", "dollar"] },
  { name: "hug", emoji: "🤗", keywords: ["hugging", "warm"] },
  { name: "shh", emoji: "🤫", keywords: ["quiet", "secret"] },
  { name: "liar", emoji: "🤥", keywords: ["pinocchio", "lie"] },
  { name: "zany", emoji: "🤪", keywords: ["silly", "crazy", "wild"] },
  { name: "monocle", emoji: "🧐", keywords: ["inspect", "hmm"] },
  { name: "yawn", emoji: "🥱", keywords: ["tired", "boring", "sleepy"] },
  { name: "pleading", emoji: "🥺", keywords: ["puppy eyes", "please"] },
  { name: "cursing", emoji: "🤬", keywords: ["angry", "swear"] },

  { name: "wave_emoji", emoji: "〰️", keywords: ["wavy"] },
  { name: "dog_face", emoji: "🐶", keywords: ["puppy", "cute"] },
  { name: "cat_face", emoji: "🐱", keywords: ["kitty", "cute"] },
  { name: "pig", emoji: "🐷", keywords: ["oink"] },
  { name: "frog", emoji: "🐸", keywords: ["toad", "pepe"] },
  { name: "chick", emoji: "🐥", keywords: ["bird", "baby"] },
  { name: "dragon", emoji: "🐉", keywords: ["fantasy"] },
  { name: "t_rex", emoji: "🦖", keywords: ["dinosaur"] },
  { name: "shark", emoji: "🦈", keywords: ["ocean", "jaws"] },
  { name: "spider", emoji: "🕷️", keywords: ["creepy"] },
  { name: "bat", emoji: "🦇", keywords: ["vampire", "night"] },
];
